### ISSUE TITLE
Import error in openva_pipeline

### ISSUE THREAD

**Issue by user-official** [verbal-autopsy-software/openva_pipeline#2]
While using the command import openva_pipeline as ovaPL, there is an error which says:
Import error: No module named openva_pipeline.

Please suggest the fix

**Comment by jarathomas** [comment]
Hello,

Apologies for the delayed response!  

Have you installed the openva-pipeline package?  At the terminal you can run:

pip3 install openva-pipeline --user

(the --user option installs the package in the user's home directory, as opposed to the system dir)

**Comment by user-official** [comment]
Now another issue that I have come across is in sqlitebrowser while running the final python commands. Pls check the screenshots for your reference.
![commands](https://user-images.githubusercontent.com/43280117/54508141-d32fd880-496a-11e9-89fa-03424c7b950a.png)
![sqlitebrowser](https://user-images.githubusercontent.com/43280117/54508150-dcb94080-496a-11e9-949c-dfd311cb6fba.png)

**Comment by user-official** [comment]
Thank u...error solved !
Now another issue that I have come across is in sqlite browser after running the final python commands that pull data from aggregate, analyse and assign cause of death to it. Pls check the screenshot for your reference.
![sqlitebrowser](https://user-images.githubusercontent.com/43280117/54508242-48031280-496b-11e9-9f3e-4028713e5fb6.png)

**Comment by jarathomas** [comment]
The error message you are receiving suggests a problem with the ODK form ID.  Can you please check that the form ID on your ODK Aggregate server is:

va_who_2016_11_03_v1_4_1

When accessing the ODK Aggregate server through a web browser, there is a tab near the top of the
 page entitled "Form Management" and this page should list the the Form ID you need to use.  This same Form ID should be entered into the SQLite database in the ODK_Conf table (in the odkFormID field).

**Comment by jarathomas** [comment]
Lack of feedback for a few years now, so closing this issue.  This appears like the pipeline does not have the right config info (as opposed to a problem with the code).  If it is a problem with the call to ODK Briefcase, the updated codes contain the suggested fix.
